environment:
  VERSION: 1.1

version: $(VERSION).{build}

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

configuration: Release

init:
  - cmd: echo %APPVEYOR_REPO_TAG%
  - cmd: set BUILD_VERSION=%VERSION%.%APPVEYOR_BUILD_NUMBER%
  - cmd: echo %APPVEYOR_REPO_BRANCH%
  - cmd: IF "%APPVEYOR_REPO_TAG%" == "true" (set PROJECT_VERSION=%APPVEYOR_REPO_TAG_NAME%) ELSE (IF "%APPVEYOR_REPO_BRANCH%"=="master" (set PROJECT_VERSION=%BUILD_VERSION%) ELSE (IF "%APPVEYOR_REPO_BRANCH%"=="development" (set PROJECT_VERSION=%BUILD_VERSION%-dev) ELSE (set PROJECT_VERSION=%BUILD_VERSION%-pr)))
  - cmd: echo %PROJECT_VERSION%
  - cmd: echo %APPVEYOR_BUILD_NUMBER%
  - cmd: echo %APPVEYOR_BUILD_VERSION%
  - cmd: echo %APPVEYOR_REPO_TAG_NAME%
  - cmd: echo %APPVEYOR_BUILD_FOLDER%
  - cmd: echo %APPVEYOR_PROJECT_NAME%

artifacts:
  - path: '**\bin\Release\WebcamCapturer.*.dll'
  - path: '**\*.nupkg'

install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(PROJECT_VERSION)
  assembly_file_version: $(BUILD_VERSION)
  assembly_informational_version: $(PROJECT_VERSION)

nuget:
  disable_publish_on_pr: true

before_build:
- cmd: nuget restore

build_script:
 - cmd: msbuild "WebcamCapturer.Controls.WPF\WebcamCapturer.Controls.WPF.csproj" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:GeneratePackageOnBuild=false
 - cmd: msbuild "WebcamCapturer.Controls.WinForms\WebcamCapturer.Controls.WinForms.csproj" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:GeneratePackageOnBuild=false
 - cmd: msbuild /t:pack "WebcamCapturer.Core\WebcamCapturer.Core.csproj" /p:PackageOutputPath="." -p:Authors=tester /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:GeneratePackageOnBuild=false
 - cmd: nuget pack "WebcamCapturer.Core\WebcamCapturer.Core.csproj" -Properties "Configuration=Release;Platform=AnyCPU" -IncludeReferencedProjects 
 - cmd: nuget pack "WebcamCapturer.Controls.WPF\WebcamCapturer.Controls.WPF.csproj" -Properties "Configuration=Release;Platform=AnyCPU" -IncludeReferencedProjects 
 - cmd: nuget pack "WebcamCapturer.Controls.WinForms\WebcamCapturer.Controls.WinForms.csproj" -Properties "Configuration=Release;Platform=AnyCPU" -IncludeReferencedProjects 

after_build:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: ls

deploy:
- provider: NuGet
  api_key:
    secure: QszWgain24f3hNHfeUTlnCJDVi/njNTVUcdGJTQST0a0OFn6aC6YW1Np6cqzoTNY
  on:
    APPVEYOR_REPO_TAG: true